version: '3.9'

services:
    gateway:
        build:
            context: .
            dockerfile: Backend/Gateway/Dockerfile
        ports:
            - "8081:8080"
    
    patient-service:
        build:
            context: .
            dockerfile: Backend/PS-API/Dockerfile
        ports:
            - "8082:8080"
        depends_on: 
            - gateway
    
    measurement-service:
        build:
            context: .
            dockerfile: Backend/MS-API/Dockerfile
        ports:
            - "8083:8080"
        depends_on:
            - gateway
    
    doctor-ui:
        build:
            context: Frontend/DoctorUI/
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        ports:
            - "4201:4200"
        command: [ "ng", "serve", "--host", "0.0.0.0" ]
            
    
    patient-ui:
        build:
            context: Frontend/PatientUI/
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        ports:
            - "4202:4200"
        command: [ "ng", "serve", "--host", "0.0.0.0" ]