version: '3.9'

services:
    patient-service:
        build:
            context: .
            dockerfile:
        ports:
            - "8082:8080"
    
    measurement-service:
        build:
            context: .
            dockerfile:
        ports:
            - "8083:8080"
            
