version: '3.9'

services:
    patient-service:
        build:
            context: .
            dockerfile: Backend/PS-API/Dockerfile
        ports:
            - "8082:8080"
            
    measurement-service:
        build:
            context: .
            dockerfile: Backend/MS-API/Dockerfile
        ports:
            - "8083:8080"
    gateway:
        build:
            context: .
            dockerfile: Backend/Gateway/Dockerfile
        ports:
            - "8081:8080"
    
    doctor-ui:
        build:
            context: .
            dockerfile: Frontend/DoctorUI/Dockerfile
        ports:
            - "4201:4200"
    
    patient-ui:
        build:
            context: .
            dockerfile: Frontend/PatientUI/Dockerfile
        ports:
            - "4202:4200"
            